on: push
name: Unit Tests
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: run
        uses: cedrickring/golang-action@1.5.2
        with:
          args: go test ./...
